name: Tests

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      
      - name: norme check
        run: |
          python3 -m pip install --disable-pip-version-check --no-cache-dir norminette
          norminette

