name: Basic tests

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      exe: minishell
      TERM: xterm


    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y check

      - name: Install norminette
        run: python3 -m pip install --no-cache-dir --quiet norminette
      - name: Norme check
        run: "! norminette Libft src includes | grep Error"
        continue-on-error: true
          
      - name: Make
        run: |
          make
          if [[ ! -f "${{ env.exe }}" ]]; then
            echo "Error: minishell executable not found"
            exit 1
          fi
          chmod +x "${{ env.exe }}"
          ./"${{ env.exe }}"
          exit 0

      - name: Test
        run: make check 
